"""Adding columns to users table

Revision ID: 3b150ebfd40d
Revises: 5752b6518b0a
Create Date: 2023-09-16 13:16:58.798768

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")
# revision identifiers, used by Alembic.
revision = '3b150ebfd40d'
down_revision = '5752b6518b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('street_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('account_type', sa.Enum('AccountType'), nullable=False))
        batch_op.add_column(sa.Column('membership', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint("unique_phone_number", ['phone'])
        batch_op.drop_column('username')

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=40), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('membership')
        batch_op.drop_column('account_type')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('street_address')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('format')

    # ### end Alembic commands ###
