"""Added columns to users

Revision ID: 5bb261675eee
Revises: 8d6948792efb
Create Date: 2023-09-15 22:39:13.889639

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")
# revision identifiers, used by Alembic.
revision = '5bb261675eee'
down_revision = '8d6948792efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('street_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('account_type', sa.Enum('Consumer', 'Admin'), nullable=False))
        batch_op.add_column(sa.Column('membership', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('unique_phone', ['phone'])
        batch_op.drop_column('username')

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=40), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('membership')
        batch_op.drop_column('account_type')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('street_address')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
